// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenseKeyApi.Migrations
{
    [DbContext(typeof(LicenseDbContext))]
    partial class LicenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("License", b =>
                {
                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeExpire200v")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeExpireDaily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LicenseKey");

                    b.ToTable("Licenses");
                });
#pragma warning restore 612, 618
        }
    }
}
